import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Cards from '../components/Cards'
import Search from '../components/Search'
import { useState,useEffect } from 'react'
import axios from 'axios'
import DropDown from '../components/DropDown'
export default function Home({users}) {
  const [searched,setSearched] = useState("");
  const [type,setType] = useState("");
  const [filteredUsers,setFilteredUsers] = useState(users);
  const requestSearch = (searchedVal) => {
    if(searchedVal == ""){
      setFilteredUsers(users)
    }
      const filter1 = users.filter((obj) => {
        const fullname = obj.fname + obj.lname
        return fullname.toLowerCase().includes(searchedVal.toLowerCase());
      });
      const filtered = filter1.filter((obj) => {
        return obj.category.toLowerCase().includes(type.toLowerCase());
      });
      setFilteredUsers(filtered);

  };
  useEffect(()=>{
    requestSearch(searched);
},[searched,type])

  return (
    <div className={styles.container}>
      <Head>
        <title>Social Links</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.searchSection}>
          <div className={styles.searchWrapper}>
            <Search searched={searched} setSearched={setSearched}/>
          </div>
          <div className={styles.dropDownWrapper}>
            <DropDown setType={setType} type={type}/>
          </div>
        </div>
        <div className={styles.grid}>
          <Cards users={filteredUsers}/>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://ali-yaghi-cv.web.app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            Ali Yaghi
          </span>
        </a>
      </footer>
    </div>
  )
}
export const getServerSideProps = async () => {
  const res = await axios.get("http://www.filltext.com/?rows=10&fname={firstName}&lname={lastName}&category=[%22facebook%22,%22instagram%22,%22github%22]&pretty=true");
  return {
    props: {
      users: res.data
    },
  };
}