import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
 
  return (
    <div className={styles.container}>
      <Head>
        <title>Madain Corp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>heelo</h1>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://ali-yaghi-cv.web.app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            Ali Yaghi
          </span>
        </a>
      </footer>
    </div>
  )
}